- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: installing mangodb
  ansible.builtin.package:
    name: mongodb-org
    state: present
- name: start and enable mangodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes
- name: replaceing with remote acess
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: start and enable mangodb
  ansible.builtin.service:
    name: mongod
    state: restarted