- name: "calling a task from common"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
- name: "calling a task from common"
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
- name: "doing mongodb setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup
- name: "doing systemd setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
    