- name: "app-setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: "installing python"
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: "doing systemd setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
    