- name: "app-setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: "installing GO"
  ansible.builtin.import_role:
    name: common
    tasks_from: go

- name: "doing systemd setup"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd
    